# Generated by Django 2.2.7 on 2020-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200402_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('link_to', models.URLField()),
                ('priority', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
    ]
